FarmFinanceMonitoring/urls.py
from django.contrib import admin
from django.urls import path

from finance_monitor.views import (yearly_settlement, invoices, flocks,
                                   home, download_raport, create_invoice,
                                   add_flock, delete_flock, end_flock, flock, invoice)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", home, name="home"),
    path("yearly_settlement/", yearly_settlement, name="yearly_settlement"),
    path("invoices/", invoices, name="invoices"),
    path("flocks/", flocks, name="flocks"),
    path("download_raport", download_raport, name="download_raport"),
    path("add_invoice", create_invoice, name="add_invoice"),
    path("add_flock", add_flock, name="add_flock"),
    path('delete_flock/<int:flock_id>', delete_flock),
    path('end_flock/<int:flock_id>', end_flock),

    path('flock/<int:flock_id>', flock),

    path('invoice/<int:invoice_id>', invoice),
]

finance_monitor/models.py
from datetime import timezone
from enum import Enum

from django.db import models


class InvoiceCategory(Enum):
    BREEDING_START = 1, "wystawienie kur"
    FORAGE = 2, "pasza"
    WATER = 3, "woda"
    ELECTRICITY = 4, "prąd"
    DRUGS = 5, "leki"
    WET = 6, "weterynaz"
    UTILIZATION = 7, "utylizacja"
    GAS = 8, "gaz"
    DISINFECTION = 9, "dezynfekcja"
    INSURANCE = 10, "ubezpieczenie budynków"

    @staticmethod
    def get_all():
        return [c.value for c in InvoiceCategory]


class InvoiceType(Enum):
    INCOME = 1, "przychod"
    EXPENSE = 2, "wydatek"

    @staticmethod
    def get_all():
        return [c.value for c in InvoiceType]


class ForageType(Enum):
    STARTER = 1, "starter"
    GROWLER = 2, "growler"
    FINISHER = 3, "finisher"

    @staticmethod
    def get_all():
        return [c.value for c in ForageType]


class Flock(models.Model):
    number = models.AutoField(primary_key=True)
    date_start = models.DateField(auto_now_add=True)
    data_end = models.DateField(null=True, blank=True)

    def __str__(self):
        return f'Rzut numer {self.number}'

class Invoice(models.Model):
    date = models.DateField(help_text='Data wystawienia faktury')
    cost = models.DecimalField(max_digits=10, decimal_places=2, help_text='Łączna kwota')
    type = models.IntegerField(choices=InvoiceType.get_all(), help_text='Typ (Koszt/Przychód)')
    invoice_number = models.CharField(max_length=50, help_text='Numer faktury')
    category = models.IntegerField(choices=InvoiceCategory.get_all(), help_text='Kategoria')
    flock = models.ForeignKey(Flock, on_delete=models.CASCADE, help_text='Rzut')
    amount = models.IntegerField(default=None, null=True, help_text='Ilość')
    unit_price = models.DecimalField(max_digits=10, decimal_places=2, default=None, null=True, help_text='Cena jednostkowa')
    water_usage = models.DecimalField(max_digits=10, decimal_places=2, default=None, null=True, help_text='Zużycie wody')
    forage_type = models.IntegerField(choices=ForageType.get_all(), help_text='Typ paszy', null=True)
    payment_deadline = models.DateField(help_text='Termin zapłaty', null=True)
    drug_name = models.CharField(null=True, help_text='Nazwa leku', max_length=50)

finance_monitor/forms.py
from datetime import date

from django import forms
from .models import Invoice

class InvoiceForm(forms.ModelForm):
    class Meta:
        model = Invoice
        fields = [
            'date', 'category', 'cost', 'type', 'invoice_number',
            'flock', 'amount', 'unit_price', 'water_usage', 'forage_type', 'payment_deadline', 'drug_name'
        ]
        widgets = {
            'date': forms.DateInput(attrs={'type': 'date'}),
            'category': forms.Select(attrs={'id': 'category-select'}),
        }
        labels = {
            'Data wystawienia faktury', 'Koszt', 'Typ (Koszt/Przychód)', 'Numer faktury',
            'Kategoria', 'Rzut', 'Ilość', 'Cena jednostkowa', 'Zużycie wody', 'Rodzaj Paszy', 'Termin zapłaty'
        }

    def __init__(self, *args, **kwargs):
        super(InvoiceForm, self).__init__(*args, **kwargs)

        today = date.today().strftime('%Y-%m-%d')
        self.fields['date'].widget.attrs.update({'placeholder': today})

        self.fields['amount'].required = False
        self.fields['unit_price'].required = False
        self.fields['water_usage'].required = False
        self.fields['payment_deadline'].required = False
        self.fields['forage_type'].required = False
        self.fields['drug_name'].required = False
        self.fields['unit_price'].required = False

finance_monitor/views.py
from datetime import date

from django.shortcuts import render, redirect
from django.contrib import messages
from finance_monitor.models import InvoiceType, Invoice, Flock
from .forms import InvoiceForm

def home(request):
    return render(request, 'finance_monitor/home.html')

def yearly_settlement(request):

    income_invoices = Invoice.objects.filter(type=1)
    expense_invoices = Invoice.objects.filter(type=2)

    total_income = sum(invoice.cost for invoice in income_invoices)
    total_expenses = sum(invoice.cost for invoice in expense_invoices)

    context = {
        'total_income': sum(invoice.cost for invoice in income_invoices),
        'total_expenses': sum(invoice.cost for invoice in expense_invoices),
        'balance': total_income - total_expenses,
        'total_invoices': len(income_invoices) + len(expense_invoices),
        'total_flocks': Flock.objects.count()
    }

    return render(request, 'finance_monitor/yearly_settlement.html', context)

def invoices(request):
    expenses = Invoice.objects.filter(type=2)
    incomes = Invoice.objects.filter(type=1)
    context = {
        'expenses': expenses,
        'incomes': incomes,
    }
    return render(request, 'finance_monitor/invoices.html', context)

def flocks(request):
    flocks_in_progress = Flock.objects.filter(data_end__isnull=True)
    flocks_done = Flock.objects.filter(data_end__isnull=False)
    return render(request, 'finance_monitor/flocks.html', {
        'flocks_in_progress': flocks_in_progress,
        'flocks_done': flocks_done,
    })

def download_raport(request):
    return None

def create_invoice(request):
    if request.method == 'POST':
        form = InvoiceForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('invoices')
    else:
        form = InvoiceForm()

    return render(request, 'finance_monitor/invoice_form.html', {'form': form})

def add_flock(request):
    flock = Flock(date_start=date.today())
    flock.save()
    flock_id = flock.pk
    return redirect(f'flock/{flock_id}')

def delete_flock(request, flock_id):
    flock = Flock.objects.get(pk=flock_id)
    flock.delete()
    return redirect('flocks')

def end_flock(request, flock_id):
    flock = Flock.objects.get(pk=flock_id)
    flock.data_end = date.today()
    flock.save()
    return redirect('flocks')

def flock(request, flock_id):
    flock = Flock.objects.get(pk=flock_id)
    invoices = Invoice.objects.filter(flock=flock)
    return render(request, 'finance_monitor/flock.html', {'invoices': invoices, 'flock': flock.pk})

def invoice(request, invoice_id):
    invoice = Invoice.objects.get(pk=invoice_id)
    return render(request, 'finance_monitor/invoice.html', {'invoice': invoice})

templates/finance_monitor/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>System monitorowania finansów fermy drobiu</title>
    <!-- Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'home' %}">Finanse</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'yearly_settlement' %}">Rozliczenie roczne</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'invoices' %}">Faktury</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'flocks' %}">Rzuty</a>
                </li>
            </ul>
        </div>
    </nav>

    <div class="container mt-4">
        {% block content %}
        {% endblock %}
    </div>

    <!-- Bootstrap JS and dependencies -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

templates/finance_monitor/flock.html
{% extends 'finance_monitor/base.html' %}

{% block content %}
    <div class="container">
    <h1 class="mb-4">Faktury dla rzutu numer {{ flock }}</h1>

    <div class="accordion" id="invoicesAccordion">
    
        <div class="card">
            <div class="card-header" id="headingExpenses">
                <h2 class="mb-0">
                    <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapseExpenses" aria-expanded="true" aria-controls="collapseExpenses">
                        Wydatki ⤵️
                    </button>
                </h2>
            </div>
            <div id="collapseExpenses" class="collapse show" aria-labelledby="headingExpenses" data-parent="#invoicesAccordion">
                <div class="card-body">
                    {% if expenses %}
                        <ul class="list-group">
                            {% for invoice in expenses %}
                                <a href="/invoice/{{ invoice.pk }}">
                                    <li class="list-group-item">
                                        DATA: {{ invoice.date }}: &nbsp  NUMER: {{ invoice.invoice_number }} &nbsp KWOTA: {{ invoice.amount }} PLN
                                    </li>
                                </a>
                            {% endfor %}
                        </ul>
                    {% else %}
                        <p>Brak wydatków.</p>
                    {% endif %}
                </div>
            </div>
        </div>

        <div class="card">
            <div class="card-header" id="headingIncomes">
                <h2 class="mb-0">
                    <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseIncomes" aria-expanded="false" aria-controls="collapseIncomes">
                        Przychody ⤵️
                    </button>
                </h2>
            </div>
            <div id="collapseIncomes" class="collapse" aria-labelledby="headingIncomes" data-parent="#invoicesAccordion">
                <div class="card-body">
                    {% if incomes %}
                        <ul class="list-group">
                            {% for invoice in incomes %}
                                <a href="/invoice/{{ invoice.pk }}">
                                    <li class="list-group-item">
                                        DATA: {{ invoice.date }}: &nbsp  NUMER: {{ invoice.invoice_number }} &nbsp KWOTA: {{ invoice.amount }} PLN
                                    </li>
                                </a>
                            {% endfor %}
                        </ul>
                    {% else %}
                        <p>Brak przychodów.</p>
                    {% endif %}
                </div>
            </div>
        </div>
    
        <div style="margin: 20px; display: flex; justify-content: center; align-items: center">
            <a class="btn btn-primary"href="{% url 'add_invoice' %}">Dodaj fakture</a>
        </div>
    </div>
</div>
{% endblock %}

templates/finance_monitor/flocks.html
{% extends 'finance_monitor/base.html' %}

{% block content %}
<div class="container">
    <h1 class="mb-4">Rzuty</h1>

    <div class="accordion" id="invoicesAccordion">
    
        <div class="card">
            <div class="card-header" id="headingExpenses">
                <h2 class="mb-0">
                    <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapseExpenses" aria-expanded="true" aria-controls="collapseExpenses">
                        Trwające ⤵️
                    </button>
                </h2>
            </div>
            <div id="collapseExpenses" class="collapse show" aria-labelledby="headingExpenses" data-parent="#invoicesAccordion">
                <div class="card-body">
                     {% if flocks_in_progress %}
                        <ul class="list-group">
                            {% for flock in flocks_in_progress %}
                                <a href="/flock/{{ flock.pk }}">
                                    <li class="list-group-item" >
                                        <b style="margin: 30px;">Numer: {{ flock.number }}</b>
                                        <b style="margin: 30px;">Od: {{ flock.date_start }}</b>
                                        <a style="margin: 30px;" class="btn btn-danger" href="/delete_flock/{{ flock.pk }}">Usuń</a>
                                        <a style="margin: 30px;" class="btn btn-primary" href="/end_flock/{{ flock.pk }}">Zakończ</a>
                                    </li>
                                </a>
                            {% endfor %}
                        </ul>
                    {% else %}
                        <p>Brak rzutów.</p>
                    {% endif %}
                </div>
            </div>
        </div>

        <div class="card">
            <div class="card-header" id="headingIncomes">
                <h2 class="mb-0">
                    <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseIncomes" aria-expanded="false" aria-controls="collapseIncomes">
                        Zakończone ⤵️
                    </button>
                </h2>
            </div>
            <div id="collapseIncomes" class="collapse" aria-labelledby="headingIncomes" data-parent="#invoicesAccordion">
                <div class="card-body">
                    {% if flocks_done %}
                        <ul class="list-group">
                            {% for flock in flocks_done %}
                                <a href="/flock/{{ flock.pk }}">
                                    <li class="list-group-item" >
                                        <b style="margin: 30px;">Numer: {{ flock.number }}</b>
                                        <b style="margin: 30px;">Od: {{ flock.date_start }}</b>
                                        <b style="margin: 30px;">Do: {{ flock.date_end }}</b>
                                        <a style="margin: 30px;" class="btn btn-danger" href="/delete_flock/{{ flock.pk }}">Usuń</a>
                                    </li>
                                </a>
                            {% endfor %}
                        </ul>
                    {% else %}
                        <p>Brak rzutów.</p>
                    {% endif %}
                </div>
            </div>
        </div>
    
        <div style="margin: 20px; display: flex; justify-content: center; align-items: center">
            <a class="btn btn-primary" href="{% url 'add_flock' %}">Utwórz rzut</a>
        </div>
    </div>
</div>
{% endblock %}

templates/finance_monitor/home.html
{% extends 'finance_monitor/base.html' %}

{% block content %}
<div class="jumbotron">
    <h1 class="display-4" style="display: flex; justify-content: center">Monitorowanie finansów fermy drobiu</h1>
    <p class="lead"></p>
    <hr class="my-4">
    
    <style>
        a {
            width: 250px;
        }
    </style>

    <div style="display: flex; align-items: center; justify-content: center; flex-direction: column">
    <a class="btn btn-primary btn-lg" href="{% url 'yearly_settlement' %}" role="button">Podsumowanie roczne</a>
    <p>Zobacz podsumowanie wydatków i przychodzów z całego roku</p>
    
    <a class="btn btn-primary btn-lg" href="{% url 'invoices' %}" role="button">Faktury</a>
    <p>Lista twoich faktur</p>
    
    <a class="btn btn-primary btn-lg" href="{% url 'flocks' %}" role="button">Rzuty</a>
    <p>Lista twoich rzutów</p>
    </div>
</div>
{% endblock %}

templates/finance_monitor/invoice.html
{% extends 'finance_monitor/base.html' %}

{% block content %}
	<h1 class="mb-4">Faktura nr {{ invoice.invoice_number }}</h1>
    
    <ul class="list-group">
        {% if invoice.date %}
        <li class="list-group-item"><strong>Data:</strong> {{ invoice.date }}</li>
        {% endif %}
        
        {% if invoice.cost %}
        <li class="list-group-item"><strong>Łączna kwota:</strong> {{ invoice.cost }}</li>
        {% endif %}
        
        {% if invoice.type %}
        <li class="list-group-item"><strong>Typ:</strong> {{ invoice.get_type_display }}</li>
        {% endif %}
        
        {% if invoice.category %}
        <li class="list-group-item"><strong>Kategoria:</strong> {{ invoice.get_category_display }}</li>
        {% endif %}
        
        {% if invoice.flock %}
        <li class="list-group-item"><strong>Rzut:</strong> {{ invoice.flock }}</li>
        {% endif %}
        
        {% if invoice.amount %}
        <li class="list-group-item"><strong>Ilość:</strong> {{ invoice.amount }}</li>
        {% endif %}
        
        {% if invoice.unit_price %}
        <li class="list-group-item"><strong>Cena jednostkowa:</strong> {{ invoice.unit_price }}</li>
        {% endif %}
        
        {% if invoice.water_usage %}
        <li class="list-group-item"><strong>Zużycie wody:</strong> {{ invoice.water_usage }}</li>
        {% endif %}
        
        {% if invoice.forage_type %}
        <li class="list-group-item"><strong>Typ paszy:</strong> {{ invoice.get_forage_type_display }}</li>
        {% endif %}
        
        {% if invoice.payment_deadline %}
        <li class="list-group-item"><strong>Termin zapłaty:</strong> {{ invoice.payment_deadline }}</li>
        {% endif %}
        
        {% if invoice.drug_name %}
        <li class="list-group-item"><strong>Nazwa leku:</strong> {{ invoice.drug_name }}</li>
        {% endif %}
    </ul>
    
{% endblock %}

templates/finance_monitor/invoice_form.html
{% extends 'finance_monitor/base.html' %}

{% block content %}
<div class="container">
    <h1 class="text-center mb-4">Dodaj Fakturę</h1>
    
    <div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header bg-primary text-white">
                    <h4 class="mb-0">Formularz faktury</h4>
                </div>
                <div class="card-body">
                    <form method="post" novalidate>
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="mb-3" id="{{ field.label }}">
                                <label for="{{ field.id_for_label }}" class="form-label">{{ field.help_text }}</label>
                                {{ field }}
                                {% if field.id_for_label == 'id_flock' %}
                                    <div style="font-size: 10px">Wybierz odpowiedni rzut z listy, jesli jest pusta, utwórzy nowy w sekcji "Rzuty"</div>
                                {% endif %}
                                {% if field.errors %}
                                    <div class="text-danger">
                                        {{ field.errors }}
                                    </div>
                                {% endif %}
                            </div>
                        {% endfor %}
                        
                        <div class="d-grid">
                            <button type="submit" class="btn btn-primary btn-block">Dodaj</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div></div>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        const categorySelect = document.getElementById('category-select');
        const amountField = document.getElementById('Amount');
        const unitPriceField = document.getElementById('Unit price');
        const waterUsageField = document.getElementById('Water usage');
        const forageTypeField = document.getElementById('Forage type');
        const paymentDeadline = document.getElementById('Payment deadline');
        const drugName = document.getElementById('Drug name')
        
        function toggleFields() {
            const category = categorySelect.value;
            amountField.style.display = 'none';
            unitPriceField.style.display = 'none';
            waterUsageField.style.display = 'none';
            forageTypeField.style.display = 'none';
            paymentDeadline.style.display = 'none';
            drugName.style.display = 'none';

            if (category === '1') {
                amountField.style.display = 'block';
                unitPriceField.style.display = 'block';
            } else if (category === '2') {
                amountField.style.display = 'block';
                unitPriceField.style.display = 'block';
                forageTypeField.style.display = 'block'
            } else if (category === '3') {
                waterUsageField.style.display = 'none';
            } else if (category === '5') {
                amountField.style.display = 'block';
                unitPriceField.style.display = 'block';
                drugName.style.display = 'block';
            }
            else if (category === '8') {
                amountField.style.display = 'block';
                unitPriceField.style.display = 'block';
            }   
            else if (category === '10') {
                paymentDeadline.style.display = 'block'
            }   
        }

        categorySelect.addEventListener('change', toggleFields);

        toggleFields();
    });
</script>
{% endblock %}

templates/finance_monitor/invoices.html
{% extends 'finance_monitor/base.html' %}

{% block content %}
<div class="container">
    <h1 class="mb-4">Faktury</h1>

    <div class="accordion" id="invoicesAccordion">
    
        <div class="card">
            <div class="card-header" id="headingExpenses">
                <h2 class="mb-0">
                    <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapseExpenses" aria-expanded="true" aria-controls="collapseExpenses">
                        Wydatki ⤵️
                    </button>
                </h2>
            </div>
            <div id="collapseExpenses" class="collapse show" aria-labelledby="headingExpenses" data-parent="#invoicesAccordion">
                <div class="card-body">
                    {% if expenses %}
                        <ul class="list-group">
                            {% for invoice in expenses %}
                                <a href="/invoice/{{ invoice.pk }}">
                                    <li class="list-group-item">
                                        DATA: {{ invoice.date }}: &nbsp  NUMER: {{ invoice.invoice_number }} &nbsp KWOTA: {{ invoice.amount }} PLN
                                    </li>
                                </a>
                            {% endfor %}
                        </ul>
                    {% else %}
                        <p>Brak wydatków.</p>
                    {% endif %}
                </div>
            </div>
        </div>

        <div class="card">
            <div class="card-header" id="headingIncomes">
                <h2 class="mb-0">
                    <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseIncomes" aria-expanded="false" aria-controls="collapseIncomes">
                        Przychody ⤵️
                    </button>
                </h2>
            </div>
            <div id="collapseIncomes" class="collapse" aria-labelledby="headingIncomes" data-parent="#invoicesAccordion">
                <div class="card-body">
                    {% if incomes %}
                        <ul class="list-group">
                            {% for invoice in incomes %}
                                <a href="/invoice/{{ invoice.pk }}">
                                    <li class="list-group-item">
                                        DATA: {{ invoice.date }}: &nbsp  NUMER: {{ invoice.invoice_number }} &nbsp KWOTA: {{ invoice.amount }} PLN
                                    </li>
                                </a>
                            {% endfor %}
                        </ul>
                    {% else %}
                        <p>Brak przychodów.</p>
                    {% endif %}
                </div>
            </div>
        </div>
    
        <div style="margin: 20px; display: flex; justify-content: center; align-items: center">
            <a class="btn btn-primary"href="{% url 'add_invoice' %}">Dodaj fakture</a>
        </div>
    </div>
</div>
{% endblock %}

templates/finance_monitor/yearly_settlement.html
{% extends 'finance_monitor/base.html' %}

{% block content %}
    <style>
        body {
            font-family: Arial, sans-serif;
        }
        .container {
            text-align: center;
            padding: 20px;
        }
        .card {
            border: 1px solid #ddd;
            border-radius: 4px;
            padding: 20px;
            margin-bottom: 20px;
        }
        a {
            width: 200px;
        }
    </style>
    
    <div class="container">
        <h1>Podsumowanie Roczne</h1>

        <div class="card">
            <p><strong>Łączne przychody:</strong> {{ total_income }} PLN</p>
            <p><strong>Łączne wydatki:</strong> {{ total_expenses }} PLN</p>
            <p><strong>Zysk netto:</strong> {{ balance }} PLN</p>
            <p><strong>Łączna liczba faktur:</strong> {{ total_invoices }}</p>
            <p><strong>Łączna liczba rzutów:</strong> {{ total_flocks }}</p>
            
             <p><a class="btn btn-secondary" href="{% url 'invoices' %}" role="button">Twoje faktury</a>
            <br>
             <p><a class="btn btn-secondary" href="{% url 'flocks' %}" role="button">Twoje rzuty</a>
            <br>
            <p><a class="btn btn-primary" href="{% url 'download_raport' %}" role="button">Pobierz raport</a>
            <p>Roczny raport podsumuwujący koszty i przychody</p></p>
        
            
        </div>
    
        
    </div>
{% endblock %}